site_name: Documentació IAW

theme:
  name: material
  palette:
    # Mode clar (per defecte)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

    # Mode fosc automàtic
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Introducción: index.md
  - Prácticas:
      - Práctica 1: Practica1.md
